trigger:
  branches:
    include:
      - main
      - develop

pool:
  name: 'Default'

variables:
  modulePath: 'projet1-main'
  acrLoginServer: 'acrabraredevops.azurecr.io'
  acrUsername: 'acrabraredevops'
  imageName: 'projet1'
  imageTag: '$(Build.BuildId)'
  namespace: 'springapp-prod'

steps:
- checkout: self
  displayName: 'Checkout code'

- script: |
    cd $(modulePath)
    mvn test
  displayName: 'CI - Run Unit Tests'
  continueOnError: false

- script: |
    cd $(modulePath)
    mvn clean package -DskipTests
  displayName: 'CI - Build Spring Boot'

- script: |
    cd $(modulePath)
    mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
      -Dsonar.projectKey=musee-virtuel \
      -Dsonar.projectName='Musee Virtuel' \
      -Dsonar.host.url=http://localhost:9000 \
      -Dsonar.login=$(SONAR_TOKEN)
  displayName: 'CI - SonarQube Analysis'
  continueOnError: true

- script: |
    echo $(ACR_PASSWORD) | docker login $(acrLoginServer) \
      -u $(acrUsername) --password-stdin
  displayName: 'CI - Login to ACR'

- script: |
    docker build \
      -t $(acrLoginServer)/$(imageName):$(imageTag) \
      -t $(acrLoginServer)/$(imageName):latest \
      $(modulePath)
  displayName: 'CI - Build Docker Image'

- script: |
    docker push $(acrLoginServer)/$(imageName):$(imageTag)
    docker push $(acrLoginServer)/$(imageName):latest
  displayName: 'CI - Push Docker Image to ACR'

- script: |
    minikube image load $(acrLoginServer)/$(imageName):$(imageTag) --profile azure-projet
    echo "Image loaded into Minikube successfully"
    minikube image ls --profile azure-projet | grep $(imageName)
  displayName: 'CI - Load Image into Minikube'

- script: |
    helm upgrade --install springapp ./helm/springapp \
      --namespace $(namespace) \
      --set image.repository=$(acrLoginServer)/$(imageName) \
      --set image.tag=$(imageTag) \
      --set image.pullPolicy=IfNotPresent \
      --wait \
      --timeout 8m
  displayName: 'CD - Deploy to Kubernetes'

- script: |
    kubectl rollout status deployment/springapp-deployment \
      -n $(namespace) --timeout=300s
    echo "=== Pods ==="
    kubectl get pods -n $(namespace)
    echo "=== Services ==="
    kubectl get svc -n $(namespace)
    echo "=== HPA ==="
    kubectl get hpa -n $(namespace)
  displayName: 'CD - Verify Deployment'

- script: |
    sleep 30
    STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://springapp.local)
    echo "HTTP Status: $STATUS"
    if [ "$STATUS" != "200" ]; then
      echo "Application not responding!"
      exit 1
    fi
    echo "Application is UP and running!"
  displayName: 'CD - Health Check'
